//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnitTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///&lt;!doctype html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;script data-ad-client=&quot;ca-pub-5430101290255408&quot; async src=&quot;https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js&quot; type=&quot;849ee89f1e8d38936c8551de-text/javascript&quot;&gt;&lt;/script&gt;
        ///    &lt;meta charset=&quot;utf-8&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1, shrink-to-fit=no&quot;&gt;
        ///    &lt;meta name=&quot;theme-color&quot; content=&quot;#ffc107&quot; /&gt;
        ///    &lt;title&gt;People Search by Name for Rob Platt in Lakebay, WA at Cyber Background Checks&lt;/title&gt;
        ///    &lt;meta [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CyberBackgroundChecksSample {
            get {
                return ResourceManager.GetString("CyberBackgroundChecksSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html lang=&quot;en&quot; class=&quot;page-list has-ads has-map&quot;&gt;&lt;head&gt;
        ///&lt;meta charset=&quot;utf-8&quot;&gt;
        ///&lt;title&gt;John Doe in New York, NY | Fast and Free People Search of Public Records&lt;/title&gt;
        ///&lt;meta name=&quot;description&quot; content=&quot;We found John Doe in New York, NY (New York). Fast and FREE people search provides current address, phone, email, relatives, criminal records &amp;amp; more. 100% FREE!&quot;&gt;
        ///&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1, maximum-scale=2, user-scalable=1, shrink-to-fit=no&quot;&gt;
        ///&lt;meta name=&quot;apple [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FastPeopleSearchSample {
            get {
                return ResourceManager.GetString("FastPeopleSearchSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html lang=&quot;en&quot;&gt;&lt;head&gt;
        ///&lt;meta charset=&quot;utf-8&quot;&gt;
        ///&lt;title&gt;Search People FREE with the Name John Doe in New York, New York&lt;/title&gt;
        ///&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1, shrink-to-fit=no&quot;&gt;
        ///&lt;meta name=&quot;description&quot; content=&quot;Search for John Doe in New York, New York, get started for free and find contact information, address and phone for anyone. Try SearchPeopleFREE.com Today!&quot;&gt;
        ///&lt;meta property=&quot;og:title&quot; content=&quot;Search People FREE with the Name John Doe in New York, New York&quot;&gt;
        ///&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SearchPeopleFreeSample {
            get {
                return ResourceManager.GetString("SearchPeopleFreeSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot;&gt;
        ///    &lt;title&gt;Rob Platt in Lakebay, WA - Free Reverse Phone, Address, Email, Background Info&lt;/title&gt;
        ///    &lt;meta name=&quot;description&quot; content=&quot;We found Rob Platt in Lakebay, WA - 100% Free Background Search with latest address, phone, email, relatives, neighbors, associates, criminal records&quot;&gt;
        ///    &lt;meta name=&quot;robots&quot; content=&quot;index, follow&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot;&gt;
        ///    &lt;meta name=&quot;applicati [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SmartBackgroundChecksSample {
            get {
                return ResourceManager.GetString("SmartBackgroundChecksSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot;&gt;
        ///    &lt;title&gt;John Doe in New York, NY - Records Found&lt;/title&gt;
        ///    &lt;meta name=&quot;robots&quot; content=&quot;NOARCHIVE&quot;&gt;
        ///    &lt;link rel=&quot;canonical&quot; href=&quot;https://www.truepeoplesearch.com/find/doe/john/area/ny/new_york&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0, maximum-scale=5&quot;&gt;
        ///    &lt;meta name=&quot;format-detection&quot; content=&quot;telephone=no&quot;&gt;
        ///    &lt;meta name=&quot;apple-mobile-web-app-title&quot; content=&quot;TruePeopleSearch.com&quot;&gt;
        ///    &lt;meta name=&quot;theme-c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TruePeopleSearchSample {
            get {
                return ResourceManager.GetString("TruePeopleSearchSample", resourceCulture);
            }
        }
    }
}
